Bank_Management/Banking_management/Banking_management/urls.py
from django.contrib import admin
from django.urls import include, path
from User import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/', include('Admin.urls')), 
    path('User/', include('User.urls')), 
    path('',views.index,name='index'),
]

Bank_Management/Banking_management/User/urls.py
from django.urls import path

from User import views




app_name = 'User'

urlpatterns = [
        path('index/', views.index, name='index'),
        path('register/', views.register, name='register'),
        path('login/', views.login, name='login'),
        path('user_home/', views.user_home, name='user_home'),
        path('profile/', views.user_profile, name='user_profile'),
        path('add-deposit/', views.deposit, name='deposit'),
        path('add-transfer/',views.transfer, name='transfer'),
        path('get-user-details/',views.get_user_details, name='get_user_details'),
        path('transaction-details/', views.transaction_details, name='transaction_details'),
        path('register_complaint/', views.register_complaint, name='register_complaint'),
        path('complaint-list/', views.complaint_list, name='complaint_list'),
        path('update_password/', views.update_password, name='update_password'),
        
        ]

Bank_Management/Banking_management/User/models.py
import random
from django.db import models
from django.utils import timezone

# Create your models here.
from django.db import models


class User(models.Model):
    ACCOUNT_TYPE_CHOICES = (
        ('salary', 'Salary Account'),
        ('student', 'Student Account'),
        ('savings', 'Savings Account'),
        ('current', 'Current Account'),
        ('joint', 'Joint Account'),
    )
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15, unique=True)
    address = models.CharField(max_length=255)
    account_number = models.CharField(max_length=20, unique=True, blank=True)
    password = models.CharField(max_length=128)  
    date_joined = models.DateTimeField(default=timezone.now)
    Adhaar = models.CharField(max_length=16, unique=True)
    Pan = models.CharField(max_length=15, unique=True)
    vstatus=models.IntegerField(default=0)
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPE_CHOICES, default='savings')
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    

    def save(self, *args, **kwargs):
        if not self.account_number:
            self.account_number = self.generate_account_number()
        super(User, self).save(*args, **kwargs)

    def generate_account_number(self):
        account_number = str(random.randint(1000000000, 9999999999))
        while User.objects.filter(account_number=account_number).exists():
            account_number = str(random.randint(1000000000, 9999999999))
        return account_number



class Transaction(models.Model):
    TRANSACTION_TYPE_CHOICES = (
        ('credit', 'Credit'),
        ('debit', 'Debit'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Link transaction to a user
    transaction_type = models.CharField(max_length=6, choices=TRANSACTION_TYPE_CHOICES)  # Credit or Debit
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Transaction amount
    balance_amount = models.DecimalField(max_digits=10, decimal_places=2)  # User's balance after the transaction
    debit_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)  # Optional debit amount
    credit_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)  # Optional credit amount
    timestamp = models.DateTimeField(default=timezone.now)
    recipient = models.ForeignKey(User, related_name='received_transactions', on_delete=models.CASCADE)  # Recipient
    
    
class Complaint(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('resolved', 'Resolved'),
        ('rejected', 'Rejected'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complaints')  # Link to the user
    title = models.CharField(max_length=255)  # Title of the complaint
    description = models.TextField()  # Detailed description of the complaint
    created_at = models.DateTimeField(default=timezone.now)  # Date and time of complaint creation
    status = models.CharField(max_length=10, default='unresolved')   # Current status of the complaint
    response = models.TextField(blank=True, null=True)  # Admin's response to the complaint
    responded_at = models.DateTimeField(blank=True, null=True) 

Bank_Management/Banking_management/User/views.py
from datetime import timezone
from django.shortcuts import redirect, render
from django.contrib import messages
from decimal import Decimal
from Admin.models import Admintable
from .models import Complaint, Transaction, User
# Create your views here.


def index(request):
    return render(request,'User/index.html')

#////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

def user_home(request):
    return render(request,'User/user_home.html')

#////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        full_name = request.POST.get('full_name')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        address = request.POST.get('address')
        pan = request.POST.get('pan')
        adhaar = request.POST.get('adhaar')
        account_type = request.POST.get('account_type')
        password = request.POST.get('password')

        if not all([username, full_name, phone_number, email, address, pan, adhaar, account_type, password]):
            messages.error(request, 'Please fill out all required fields.')
            return render(request, 'User/register.html')

        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exists.')
            return render(request, 'User/register.html')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email already exists.')
            return render(request, 'User/register.html')

        user = User(
            username=username,
            full_name=full_name,
            phone_number=phone_number,
            email=email,
            address=address,
            password=password,
            Pan=pan,
            Adhaar=adhaar,
            account_type=account_type,
        )
        user.save()  

        messages.success(request, 'Your account has been created successfully!')
        return redirect('User:login') 
    
    return render(request, 'User/register.html')


#////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

def login(request):
    if request.method=="POST":
        email=request.POST.get('email')
        password=request.POST.get('password')
        Ulogin=User.objects.filter(email=email,password=password,vstatus=True).count()
        Alogin=Admintable.objects.filter(email=email,password=password).count()


        if Ulogin > 0:
            uadmin=User.objects.get(email=email,password=password,vstatus=1)
            request.session['Uid']=uadmin.id
            return redirect('User:user_home')
        elif Alogin > 0:
            Aadmin=Admintable.objects.get(email=email,password=password)
            request.session['Aid']=Aadmin.id
            return redirect('Admin:admin_home')
        
        else:
            error="Invalid Credentials!!"
            return render(request,"User/Login.html",{'ERR':error})
    else:
        return render(request, "User/Login.html")
    
    


#////////////////////////////////////////////////////////////////////////

def user_profile(request):
    if 'Uid' in request.session:
        user_id = request.session['Uid']
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            messages.error(request, "User does not exist.")
            return redirect('User:login')

        return render(request, 'User/profile.html', {'user': user})
    else:
        messages.error(request, "You must be logged in to view your profile.")
        return redirect('User:login')
    
#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    

def deposit(request):
    if 'Uid' not in request.session:
        messages.error(request, "You need to be logged in to make a deposit.")
        return redirect('User:login')

    if request.method == 'POST':
        amount = request.POST.get('amount')
        
        if not amount or Decimal(amount) <= 0:
            messages.error(request, "Please enter a valid amount.")
            return render(request, 'User/deposit.html')

        user = User.objects.get(id=request.session['Uid'])
        
        deposit_amount = Decimal(amount)
        
        user.balance += deposit_amount 
        user.save()

        transaction = Transaction(
            user=user,
            transaction_type='credit',
            amount=deposit_amount,
            balance_amount=user.balance,
            credit_amount=deposit_amount,
        )
        transaction.save()

        messages.success(request, "Deposit successful!")
        return redirect('User:user_profile') 
    return render(request, 'User/deposit.html')

#////////////////////////////////////////////////////////////////////////////

def transfer(request):
    if 'Uid' not in request.session:
        messages.error(request, "You need to be logged in to transfer money.")
        return redirect('User:login')

    user = User.objects.get(id=request.session['Uid'])

    if request.method == 'POST':
        recipient_account_number = request.POST.get('recipient_account_number')
        transfer_amount = request.POST.get('amount')

        if not transfer_amount or Decimal(transfer_amount) <= 0:
            messages.error(request, "Please enter a valid amount.")
            return render(request, 'User/transfer.html', {'user': user})  
        try:
            recipient = User.objects.get(account_number=recipient_account_number)
        except User.DoesNotExist:
            messages.error(request, "Recipient account number is invalid.")
            return render(request, 'User/transfer.html', {'user': user}) 

        if recipient.vstatus == 0:
            messages.error(request, "Recipient's account is not approved.")
            return render(request, 'User/transfer.html', {'user': user})  

        transfer_amount = Decimal(transfer_amount)

        if user.balance < transfer_amount:
            messages.error(request, "Insufficient balance for this transaction.")
            return render(request, 'User/transfer.html', {'user': user})  

        user.balance -= transfer_amount
        recipient.balance += transfer_amount

        user.save()
        recipient.save()

        Transaction.objects.create(
            user=user,
            transaction_type='debit',
            amount=transfer_amount,
            balance_amount=user.balance,
            debit_amount=transfer_amount,
        )

        Transaction.objects.create(
            user=recipient,
            transaction_type='credit',
            amount=transfer_amount,
            balance_amount=recipient.balance,
            credit_amount=transfer_amount,
        )

        messages.success(request, "Transfer successful!")
        return redirect('User:user_profile')  

    return render(request, 'User/transfer.html', {'user': user})  


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

from django.http import JsonResponse

def get_user_details(request):
    if request.method == 'GET':
        account_number = request.GET.get('account_number')
        try:
            user = User.objects.get(account_number=account_number)
            if user.vstatus == 1: 
                return JsonResponse({
                    'success': True,
                    'full_name': user.full_name,
                    'email': user.email
                })
            else:
                return JsonResponse({'success': False, 'message': "User account not approved."})
        except User.DoesNotExist:
            return JsonResponse({'success': False, 'message': "User does not exist."})

    return JsonResponse({'success': False, 'message': "Invalid request."})


#//////////////////////////////////////////////////////////////////////////////////////////////////////////

def transaction_details(request):
    if 'Uid' not in request.session:
        messages.error(request, "You need to be logged in to view transaction details.")
        return redirect('User:login')

    user = User.objects.get(id=request.session['Uid'])
    
    transactions = Transaction.objects.filter(user=user).order_by('-timestamp') 

    return render(request, 'User/transaction_details.html', {'user': user, 'transactions': transactions})


#////////////////////////////////////////////////////////////////////////////////////////////////////////////


def register_complaint(request):
    if 'Uid' not in request.session:
        messages.error(request, "You need to be logged in to register a complaint.")
        return redirect('User:login')

    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')

        complaint = Complaint.objects.create(
            user=User.objects.get(id=request.session['Uid']),
            title=title,
            description=description
        )
        messages.success(request, "Complaint registered successfully!")
        return redirect('User:complaint_list')  

    return render(request, 'User/register_complaint.html') 

def complaint_list(request):
    if 'Uid' not in request.session:
        messages.error(request, "You need to be logged in to view your complaints.")
        return redirect('User:login')

    user = User.objects.get(id=request.session['Uid'])
    complaints = Complaint.objects.filter(user=user).order_by('-created_at') 

    return render(request, 'User/complaint_list.html', {'complaints': complaints})


#/////////////////////////////////////////////////////////////////////////////////////////////////////

def update_password(request):

Bank_Management/Banking_management/User/templates/User/complaint_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complaint List</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <style>
    nav{
        text-transform: uppercase;
      }
   </style>
</head>
<body>

    <div class="container">
        <h1>Complaint List</h1>

        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Date Submitted</th> <!-- This will show created_at -->
                    <th>Responded </th> <!-- This will show created_at -->
                </tr>
            </thead>
            <tbody>
                {% for complaint in complaints %}
                    <tr>
                        <td>{{ complaint.title }}</td>
                        <td>{{ complaint.description }}</td>
                        <td class="status {% if complaint.status == 'resolved' %}resolved{% else %}unresolved{% endif %}">
                            {{ complaint.status|title }} <!-- Show the status, e.g., 'Resolved' or 'Unresolved' -->
                        </td>
                        <td>{{ complaint.created_at }}</td> <!-- Use created_at for submission date -->
                        <td>{{ complaint.response }}</td> <!-- Use created_at for submission date -->
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">No complaints found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</body>
</html>

Bank_Management/Banking_management/User/templates/User/deposit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Transaction</title>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/4c235e51ee.js" crossorigin="anonymous"></script>
  <style>
    /* Styling for the card */
    nav{
        text-transform: uppercase;
      }
    .card {
      box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);
      border-radius: 10px;
      overflow: hidden;
      background-color: #fff;
    }

    /* Styling for the header */
    .card-header {
      background-color: #28a745;
      color: white;
      padding: 20px;
      border-bottom: 0;
      text-align: center;
      font-weight: bold;
      text-transform: uppercase;
    }

    /* Styling for the form */
    .card-body {
      padding: 30px;
      font-size: 16px;
    }

    .form-label {
      font-weight: bold;
      color: #28a745;
    }

    .form-control {
      border-radius: 5px;
      padding: 10px;
      font-size: 16px;
    }

    /* Button styling */
    button {
      width: 100%;
      padding: 10px;
      margin-top: 20px;
      background-color: #28a745;
      color: white;
      border: none;
      border-radius: 5px;
      font-size: 18px;
      font-weight: bold;
      transition: background-color 0.3s;
    }

    button:hover {
      background-color: #218838;
      cursor: pointer;
    }

    /* Container styling */
    .container {
      max-width: 500px;
      margin: 60px auto;
    }

    /* Responsive design */
    @media (max-width: 768px) {
      .container {
        padding: 10px;
      }
    }
  </style>
</head>

<body>
  <!-- navbar start -->
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'User:user_home'%}"><b>
          <h1><i>Bank-Management</i></h1>
        </b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'User:user_home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'User:user_profile'%}">user_profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'User:deposit'%}">deposit</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'User:transfer'%}">transfer</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'User:transaction_details'%}">transaction_details</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'User:register_complaint'%}">register_complaint</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'User:index'%}">Logout</a>
          </li>
          <li class="nav-item dropdown">
            </a>
            <ul class="dropdown-menu">
            </ul>
          </li>
          <li class="nav-item">
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h4 class="mb-0">SELF-DEPOSIT</h4>
      </div>
      <div class="card-body">
        <img src="https://i.postimg.cc/t4RyNYyM/qrcode-icon-187848.png" alt="" srcset=""
          style="width: 140px; height: 140px; margin-left: 120px;">
        <p align="center">scan Qr for deposit amount</p>
        <form method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="amount" class="form-label">Deposit Amount:</label>
            <input type="number" name="amount" id="amount" class="form-control" required>
          </div>
          <button type="submit" class="btn btn-primary">Deposit</button>
        </form>
      </div>
    </div>
  </div>

<br>
  <!-- footer start -->
  <footer class="bg-body-tertiary text-center">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #3b5998;" href="#!"
          role="button"><i class="fab fa-facebook-f"></i></a>

        <!-- Twitter -->
        <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #55acee;" href="#!"
          role="button"><i class="fab fa-twitter"></i></a>

        <!-- Google -->
        <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #dd4b39;" href="#!"
          role="button"><i class="fab fa-google"></i></a>

        <!-- Instagram -->
        <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #ac2bac;" href="#!"
          role="button"><i class="fab fa-instagram"></i></a>

        <!-- Linkedin -->
        <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #0082ca;" href="#!"
          role="button"><i class="fab fa-linkedin-in"></i></a>
        <!-- Github -->
        <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #333333;" href="#!"
          role="button"><i class="fab fa-github"></i></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2024 Copyright: AshiQ & Swalih
      <a class="text-body" href="https://mdbootstrap.com/">bankmanagement.com</a>
    </div>
    <!-- Copyright -->
  </footer>
</body>

</html>

Bank_Management/Banking_management/User/templates/User/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/4c235e51ee.js" crossorigin="anonymous"></script>
    <style>
      /* Card styling */
      .card {
          box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);
          border-radius: 10px;
          overflow: hidden;
          background-color: #fff;
      }

      .card-header {
          background-color: #007bff;
          color: white;
          padding: 15px;
          border-bottom: 0;
          text-align: center;
          font-weight: bold;
          text-transform: uppercase;
      }

      .card-body {
          padding: 20px;
          font-size: 16px;
      }

      .card-body p {
          margin-bottom: 15px;
          font-size: 16px;
      }

      /* Styling for labels */
      .card-body strong {
          color: #007bff;
      }

      /* Button styling */
      button {
          display: block;
          width: 100%;
          padding: 10px;
          margin-top: 20px;
          background-color: #007bff;
          color: white;
          border: none;
          border-radius: 5px;
          font-size: 16px;
          font-weight: bold;
          transition: background-color 0.3s;
      }

      button:hover {
          background-color: #0056b3;
          cursor: pointer;
      }

      /* Container spacing */
      .container {
          max-width: 600px;
          margin: 40px auto;
      }

      /* Responsive design */
      @media (max-width: 768px) {
          .container {
              padding: 10px;
          }
      }
      nav{
        text-transform: uppercase;
      }
  </style>
</head>
<body>
    <!-- navbar start -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'User:user_home'%}"><b><h1><i>Bank-Management</i></h1></b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'User:user_home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:user_profile'%}">user_profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:deposit'%}">deposit</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:transfer'%}">transfer</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:transaction_details'%}">transaction_details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:register_complaint'%}">register_complaint</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:index'%}">Logout</a>
              </li>
              <li class="nav-item dropdown">
                </a>
                <ul class="dropdown-menu">
                </ul>
              </li>
              <li class="nav-item">
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <!-- navbar end -->
       <br><br><br>
      <div class="container mt-2">
        <div class="card">
            <div class="card-header">
                <h4 class="mb-0">User Profile</h4>
            </div>
            <div class="card-body">
                <p><strong>Username:</strong> {{ user.username }}</p>
                <p><strong>Full Name:</strong> {{ user.full_name }}</p>
                <p><strong>Email:</strong> {{ user.email }}</p>
                <p><strong>Phone Number:</strong> {{ user.phone_number }}</p>
                <p><strong>Address:</strong> {{ user.address }}</p>
                <p><strong>Account Number:</strong> {{ user.account_number }}</p>
                <p><strong>Account Type:</strong> {{ user.get_account_type_display }}</p>
                <p><strong>Aadhaar:</strong> {{ user.Aadhaar }}</p>
                <p><strong>PAN:</strong> {{ user.Pan }}</p>
                <p><strong>Date Joined:</strong> {{ user.date_joined }}</p>
                <form action="{% url 'User:update_password' %}" method="get">
                    <button type="submit">Update Password</button>
                </form>
            </div>
        </div>
    </div>
    <br><br><br>
     <!-- footer start -->
     <footer class="bg-body-tertiary text-center">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a
            data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #3b5998;"
              href="#!"
              role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #55acee;"
              href="#!"
              role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #dd4b39;"
              href="#!"
              role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #ac2bac;"
              href="#!"
              role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #0082ca;"
              href="#!"
              role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
            <!-- Github -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #333333;"
              href="#!"
              role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
          © 2024 Copyright: AshiQ & Swalih
          <a class="text-body" href="https://mdbootstrap.com/">bankmanagement.com</a>
        </div>
        <!-- Copyright -->
      </footer>
</body>
</html>